### ISSUE TITLE
Error when querying Firestore when the document includes a reference to another document

### ISSUE THREAD

**Issue by Jak3b0** [dappsnation/akita-ng-fire#31]
Hi,

I have a collection in Firestore that have a field of type `reference` (see https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentReference). My Akita store is derived from `EntityStore`, my query `QueryEntity` and my service `CollectionService`. 

When loading the data, I get the following error (which I do not have if I use the AngularFire2 library directly):

```
ERROR TypeError: Cannot read property 'host' of undefined
    at Object.push../node_modules/@firebase/firestore/dist/index.cjs.js.Firestore.configureClient (vendor.js:152734)
    at Object.push../node_modules/@firebase/firestore/dist/index.cjs.js.Firestore.ensureClientConfigured (vendor.js:152726)
    at Object.get [as _isTerminated] (vendor.js:152680)
    at vendor.js:125849
    at Array.forEach (<anonymous>)
    at deepFreeze (vendor.js:125842)
    at vendor.js:125852
    at Array.forEach (<anonymous>)
    at deepFreeze (vendor.js:125842)
    at vendor.js:125852

@firebase/firestore: Firestore (7.0.0): INTERNAL UNHANDLED ERROR:  TypeError: Cannot assign to read only property 'name' of object 'Error: Operation cancelled'
    at new FirestoreError (http://localhost:4200/vendor.js:132431:20)
    at DelayedOperation.push../node_modules/@firebase/firestore/dist/index.cjs.js.DelayedOperation.cancel (http://localhost:4200/vendor.js:133648:34)
    at OnlineStateTracker.push../node_modules/@firebase/firestore/dist/index.cjs.js.OnlineStateTracker.clearOnlineStateTimer (http://localhost:4200/vendor.js:144184:35)
    at OnlineStateTracker.push../node_modules/@firebase/firestore/dist/index.cjs.js.OnlineStateTracker.set (http://localhost:4200/vendor.js:144154:14)
    at RemoteStore.push../node_modules/@firebase/firestore/dist/index.cjs.js.RemoteStore.unlisten (http://localhost:4200/vendor.js:145626:41)
    at http://localhost:4200/vendor.js:149227:51
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.js:378:30)
    at Object.onInvoke (http://localhost:4200/vendor.js:71887:33)
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.js:377:36)
    at Zone.run (http://localhost:4200/polyfills.js:137:47)
```

Is there something I must do in order to be able to work with that type of field?

**Comment by GrandSchtroumpf** [comment]
Hello, can you provide some code sample, or better a stackblitz project, for me to understand better what the issue is ?

**Comment by GrandSchtroumpf** [comment]
Feel free to reopen this issue if you're still facing this problem.
